# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Deploy-main

on:
  pull_request:
    types: [closed]
    branches: [main]

permissions: write-all

jobs:
  main-merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          user: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          command: |
            cd /home/ubuntu
            sudo rm -f env.properties
            sudo echo "DDL_SET=${{secrets.DDL_SET}}" >> env.properties
            sudo echo "DEV_DB_URL=${{secrets.DEV_DB_URL}}" >> env.properties
            sudo echo "DEV_DB_USER=${{secrets.DEV_DB_USER}}" >> env.properties
            sudo echo "DEV_DB_PASSWORD=${{secrets.DEV_DB_PASSWORD}}" >> env.properties
            sudo echo "JWT_SECRET=${{secrets.JWT_SECRET}}" >> env.properties
            sudo echo "GOOGLE_KEY=${{secrets.GOOGLE_KEY}}" >> env.properties
            sudo echo "ACCESS=${{secrets.ACCESS}}" >> env.properties
            sudo echo "PASS=${{secrets.PASS}}" >> env.properties
            sudo echo "URL=${{secrets.URL}}" >> env.properties
            sudo echo "BUCKET=${{secrets.BUCKET}}" >> env.properties
            sudo chmod +x env.properties
            sudo ./deployauto.sh
